### ISSUE TITLE
Fail to install runit

### ISSUE THREAD

**Issue by djnugent** [3drobotics/solo-cli#15]
``` bash

daniel@daniel-VirtualBox:~$ solo install-runit
NOTE: this process requires simultaneous access to
Solo and to the Internet. if you have not yet done so,
run `solo wifi` to connect to Solo and to a local
wifi connection simultaneously.

connecting to solo...
waiting for Internet connectivity...

Loading cache...
Updating cache...               ######################################## [100%]


error: busybox-1.21.1-r1@cortexa9hf_vfp_neon is not available for downloading
```

Solved by a reboot. Posting for future lookup

**Comment by JonasVautherin** [comment]
I have exactly this error, and rebooting the Solo did not solve anything =/

**Comment by djnugent** [comment]
@JonasVautherin make sure you are connected to the internet. i.e. run `solo wifi` prior

**Comment by djnugent** [comment]
Edit: Make sure you are connected to wifi and if it still doesn't work then run it again. You should not need to reboot. Just run a second time.

**Comment by JonasVautherin** [comment]
I tried updating my controller + solo again, and I still get the same error. The Solo is connected to the Internet (I can ping successfully from the Solo)...

**Comment by JonasVautherin** [comment]
Running `solo install-smart` again solved my problem.

**Comment by Lybior** [comment]
Doesnt work for me, still having 
"Mac-mini-2:~ tms$ solo install-runit
NOTE: this process requires simultaneous access to
Solo and to the Internet. if you have not yet done so,
run `solo wifi` to connect to Solo and to a local
wifi connection simultaneously.

connecting to solo...
waiting for Internet connectivity...

Loading cache...
Updating cache...               ######################################## [100%]

error: busybox-1.21.1-r1@cortexa9hf_vfp_neon is not available for downloading"

**Comment by JonasVautherin** [comment]
And `solo install-smart` works?

**Comment by Lybior** [comment]
Yes, but not perfectly:
"Mac-mini-2:~ tms$ solo install-smart
NOTE: this process requires simultaneous access to
Solo and to the Internet. if you have not yet done so,
run `solo wifi` to connect to Solo and to a local
wifi connection simultaneously.

connecting to solo...
waiting for Internet connectivity...

setting up repositories.
rpmsys...
all...
cortexa9hf_vfp_neon...
cortexa9hf_vfp_neon_mx6...
imx6solo_3dr_1080p...

Loading cache...
Updating cache...               ######################################## [100%]

Fetching information for 'all'...  
-> http://solo-packages.s3-website-us-east-1.amazonaws.com/.../repomd.xml  
repomd.xml                                                               [  6%]

Fetching information for 'imx6solo_3dr_1080p'...
-> http://solo-packages.s3-website-us-east-1.amazonaws.com/.../repomd.xml  
repomd.xml                                                               [ 31%]
error: Failed acquiring release file for 'all':
error: http://solo-packages.s3-website-us-east-1.amazonaws.com/3.10.17-rt12/all/repodata/repomd.xml: [Errno -2] Name or service not known

Fetching information for 'cortexa9hf_vfp_neon_mx6'...
-> http://solo-packages.s3-website-us-east-1.amazonaws.com/.../repomd.xml  
repomd.xml                                                               [ 56%]
error: Failed acquiring release file for 'imx6solo_3dr_1080p':
error: http://solo-packages.s3-website-us-east-1.amazonaws.com/3.10.17-rt12/imx6solo_3dr_1080p/repodata/repomd.xml: [Errno -2] Name or service not known

Fetching information for 'cortexa9hf_vfp_neon'...
-> http://solo-packages.s3-website-us-east-1.amazonaws.com/.../repomd.xml  
repomd.xml                                                               [ 81%]
error: Failed acquiring release file for 'cortexa9hf_vfp_neon_mx6':
error: http://solo-packages.s3-website-us-east-1.amazonaws.com/3.10.17-rt12/cortexa9hf_vfp_neon_mx6/repodata/repomd.xml: [Errno -2] Name or service not known
error: Failed acquiring release file for 'cortexa9hf_vfp_neon':
error: http://solo-packages.s3-website-us-east-1.amazonaws.com/3.10.17-rt12/cortexa9hf_vfp_neon/repodata/repomd.xml: [Errno -2] Name or service not known

Updating cache...               ######################################## [100%]

Channels have no new packages.

smart package manager is now ready to use."

**Comment by ytlee** [comment]
hello, 

I have the same problem, can you tell me how to resolve the problem.

I had no problem running the solo install-smart

**Comment by hamishwillee** [comment]
This issue is closed. Please don't append to it.
