### ISSUE TITLE
wifi.py expecting exactly version 1.1.15

### ISSUE THREAD

**Issue by jmachuca77** [3drobotics/solo-cli#16]
I assume this works also with 1.2.0??

**Comment by jmachuca77** [comment]
Just saw the comment on the last commit. Closing this assuming there is an issue raised so that other versions are supported.

**Comment by tcr3dr** [comment]
Hi @jmachuca77,

Reopening this issue. You are correct that 1.1.15 is currently required by the WiFi script. Specific kernel drivers included by default in 1.2.0 should allow us to enable the WiFi configuration without any additional downloads, but the Python script needs to be updated. I hope to get this fixed asap.

**Comment by adriangrassi** [comment]
I too have this problem, the solo wifi needs the version to be 1.1.15, however solo updates to 1.2.0 so I can't connect to wifi. Please assist, does anyone know of a work around? I tried reverting to the 1.1.15 but only current is supported by the command.

Thanks,

-Adrian

**Comment by tcr3dr** [comment]
Hi @adriangrassi, @jmachuca77,

solo-cli has been updated to support 1.2.0 and above. The original issue involved Solo's WiFi channels often being selected at odds with that of the network you are targeting; this was aggravated when 1.2.0 was released with support for more WiFi channels.

This is fixed now by connecting to the target network first, then bringing up Solo's network afterward. Follow the on-screen instructions in `solo wifi`. Let me know if this works or if this fails for you.

**Comment by tcr3dr** [comment]
Since this issue refers to 1.2.0 support, I'm marking it as fixed. You can submit comments on this open thread if you have general issues with the wifi command: https://github.com/3drobotics/solodevguide/issues/156
